### ISSUE TITLE
[bug] `panic!` instead of `Result<_, Error>` if too few bspline elements

### ISSUE THREAD

**Issue by LU15W1R7H** [NicolasKlenert/enterpolation#14]
thread 'main' panicked at 'attempt to subtract with overflow' in
https://github.com/NicolasKlenert/enterpolation/blob/59231f4c0e2e813ff9272d76ed9d4d8f86c1a20b/src/bspline/builder.rs#L685

This happens if too few elements are passed to the builder.

I would expect this not to panic but instead return a `Err(BSplineError::TooFewElements)` from `.build()`.

**Comment by NicolasKlenert** [comment]
I agree that the correct behaviour should be the one your were expecting. This shouldn't be too hard to change, so I should get this done tommorow. Thank you for your find!
