### ISSUE TITLE
Eager implementation of common traits

### ISSUE THREAD

**Issue by TiemenSch** [NicolasKlenert/enterpolation#21]
Hi there! Thanks for a useful crate. As the author of `palette` seems to be exploring using your crate's functionality for gradient interpolation, I thought I might as well take the plunge.

However, would you consider implementing common traits for the types in this crate? 
https://rust-lang.github.io/api-guidelines/interoperability.html

I personally encountered this when some of my code required `PartialEq` to be implemented for `Linear`. My current workaround relies on comparing the values for the `Debug` representation, but that doesn't seem all too future-proof or efficient.

**Comment by NicolasKlenert** [comment]
Hi! That is a good catch! `PartialEq` and `Eq` should be implemented for the curves.

However I would still be interested in your use case. Correctly comparing curves (even if they or only `Linear`) is really difiicult (more so than floats and even that is not as easy) and maybe using some norm would be a better fit for you. Could you elaborate a bit what your code wants to do with `Linear`?

**Comment by TiemenSch** [comment]
I'm storing color palettes in a Yewdux store. It relies on PartialEq by default when checking if a store's contents are changed.

For me it would suffice to check if the interpolator is of the same class and has the same properties and not necessarily if they would be "equivalent" in usage (e.g. a manual Linear with equidistant knots versus an Equidistant or other struct type may result in not-equal).

**Comment by NicolasKlenert** [comment]
Hey, I was rather busy and I noticed I never gave you an answer. As this change is not huge I thought I could solve this in a few days and close this issue. Well now it is still here. I still have the plan to do it in the next few days. So just that you know: I plan to implement it and it will definitly be in the next version. Sorry for the long wait!
